name: Build and Push Docker Image


on: workflow_dispatch

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lgoin to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/bild-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reo-project:latest